### ISSUE TITLE
Getting [Doctrine\Common\Persistence\Mapping\MappingException] with multiple orm mappings

### ISSUE THREAD

**Issue by belackriv** [doctrine/DoctrineMigrationsBundle#136]
This is my config.yml
```
doctrine:
    dbal:
        driver: "%postgres_driver%"
        host: "%postgres_host%"
        port: "%postgres_port%"
        dbname: "%postgres_database%"
        user: "%postgres_username%"
        password: "%postgres_password%"
        charset: UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        #auto_mapping: true
        mappings:
            AppBundle: ~
            Money:
                mapping: true
                type: yml
                dir: "%kernel.root_dir%/../src/AppBundle/Resources/config/doctrine/Money"
                alias: ~
                prefix: "Money"
                is_bundle: false


doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: AppBundle\DoctrineMigrations
    table_name: _doctrine_migration_versions
    name: App Migrations
```
The actual error looks like "Class 'AppBundle\Entity/Money\Currency' does not exist".  I'm using a Money class that is not namespaced to my bundle.
