### ISSUE TITLE
Migrations --configuration namespace

### ISSUE THREAD

**Issue by LogansUA** [doctrine/DoctrineMigrationsBundle#150]
So, hello there.

My project configurations:
* symfony/symfony v2.8.2
* doctrine/doctrine-migrations-bundle 1.1.1

Yesterday i was trying to split databases on my project. In order to do that i need to execute specific pack of migrations on specific database so i start digging.

I found this [issue](https://github.com/doctrine/DoctrineMigrationsBundle/issues/38) and related [pull request](https://github.com/doctrine/DoctrineMigrationsBundle/pull/46) and i found [answer](https://github.com/doctrine/DoctrineMigrationsBundle/pull/46#issuecomment-75542424) but when i was trying to implement that i found bug (or feature :smile:).

So i create configuration file like that:
```YML
# My Entity Manager Doctrine Migrations Configuration
migrations_directory: "app/DoctrineMigrations/MyEntityManager"
migrations_namespace: Application\Migrations\MyEntityManager
```

And i got this `MigrationException`
```                                                                  
  [Doctrine\DBAL\Migrations\MigrationException]                                 
  Migrations namespace must be configured in order to use Doctrine migrations.
```

Well. As i'm some king of "digging expert" i get to the exception trace and found this interesting thing.

In file `AbstractFileConfiguration` line `61` there is `setConfiguration(Array $config)` function that goes through array of parameters and call specific function for specific config key.

```PHP
/**
 * @var array of possible configuration properties in migrations configuration.
 */
private $configurationProperties = [
    'name'                 => 'setName',
    'table_name'           => 'setMigrationsTableName',
    'migrations_namespace' => 'setMigrationsNamespace',
    'organize_migrations'  => 'setMigrationOrganisation',
    'migrations_directory' => 'loadMigrationsFromDirectory',
    'migrations'           => 'loadMigrations',
];
```

So when it gets to my first config parameter (`migrations_directory`) it calls `loadMigrationsFromDirectory` function which calls `registerMigrationsFromDirectory` (line `75` of `AbstractFileConfiguration`) and this function calls `validate` function (:smile:) which start to check for `migrations_namespace` value (file `Configuration` line `185`) but for now the `setConfiguration` didn't set this value so it's throw an `MigrationException`.

Setting keys in another order solves this thing:
```YML
# My Entity Manager Doctrine Migrations Configuration
migrations_namespace: Application\Migrations\MyEntityManager
migrations_directory: "app/DoctrineMigrations/MyEntityManager"
```

So this is it.

P.S. I think that this [PR](https://github.com/doctrine/DoctrineMigrationsBundle/pull/46) idea is definitely better because:
* It's really easy to use
* When you'll using `diff` (with `--em` key) command you will always be confident that migration will be created only for this connection and placed in directory for this connection, because now you can accidentally forget about `--configuration` key and it will be created in wrong place.

P.S.S. Also it would be great if we have some paragraph in docs about configuration file which should be used for `--configuration` key because i see that there are 6 of configuration keys like
```
name
table_name
migrations_namespace
organize_migrations
migrations_directory
migrations
```
but i saw only 4 of them in this [comment](https://github.com/doctrine/DoctrineMigrationsBundle/pull/46#issuecomment-75542424) and [here](http://stackoverflow.com/questions/16640503/doctrine-migrations-namespace-error)
