### ISSUE TITLE
--db option is ignored when any entity manager present (even default one)

### ISSUE THREAD

**Issue by scaytrase** [doctrine/DoctrineMigrationsBundle#163]
https://github.com/doctrine/DoctrineMigrationsBundle/blob/master/Command/Helper/DoctrineCommandHelper.php#L36-L40

```
        if (empty($managerNames)) {
            self::setApplicationConnection($application, $input->getOption('db'));
        } else {
            self::setApplicationEntityManager($application, $input->getOption('em'));
        }
```

This code ignores `--db` option if any entity manager present (and default is usualy does). So having configuration like following

```yaml
doctrine:
    dbal:
      default_connection: default
      connections:
        default:
          driver:   pdo_pgsql
          host:     "%database_host%"
          port:     "%database_port%"
          dbname:   "%database_name%"
          user:     "%database_user%"
          password: "%database_password%"
          charset:  UTF8

        migrations:
          driver:   pdo_pgsql
          host:     "%database_migrations_host%"
          port:     "%database_migrations_port%"
          dbname:   "%database_migrations_name%"
          user:     "%database_migrations_user%"
          password: "%database_migrations_password%"
          charset:  UTF8
    # ...
    orm:
      auto_generate_proxy_classes: "%kernel.debug%"
      naming_strategy: doctrine.orm.naming_strategy.underscore
      auto_mapping: true
```

Prohibits us to use separate admin connection to perform migrations with commands like (just example)

```sh
bin/console doctrine:migrations:status --db=migrations --show-versions
```
