### ISSUE TITLE
Ability to change the class template

### ISSUE THREAD

**Issue by PapsOu** [doctrine/DoctrineMigrationsBundle#199]
Is it possible to allow users to change the template used by `doctrine:migration:generate` command in order to be able to add automaticaly the ContainerAwareInterface interface and the ContainerAwareTrait trait ?

It would be great if we can set an option entry under `doctrine_migrations` key :

```yaml
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
    template: "%kernel.root_dir%/DoctrineMigrations/skeleton.tpl"
```

The template is hard coded in Doctrine\DBAL\Migrations\Tools\Console\Command\GenerateCommand class and cannot be overriden without creating a child bundle.
