### ISSUE TITLE
Diff command fails with a type error

### ISSUE THREAD

**Issue by rybakit** [doctrine/DoctrineMigrationsBundle#206]
```
[Symfony\Component\Debug\Exception\FatalThrowableError]                                                                       
Type error: Argument 1 passed to Doctrine\DBAL\Migrations\Configuration\Configuration::setCustomTemplate() must be of the type string, null given, called in .../vendor/doctrine/doctrine-migrations-bundle/Command/DoctrineCommand.php on line 71                                                         
```
config.yml:
```yaml
doctrine_migrations:
    dir_name: "%kernel.project_dir%/src/Migration"
    namespace: MyVendor\Migration
```
