### ISSUE TITLE
dir_name does not support multiple directories

### ISSUE THREAD

**Issue by precious-coder** [doctrine/DoctrineMigrationsBundle#261]
I want to use https://github.com/doctrine/migrations/pull/238 because I've migrations in my current Symfony project and in a shared bundle which sits in `/vendor`. 

```yaml
doctrine_migrations:
    dir_name:
        - '%kernel.project_dir%/src/Migrations'
        - '%kernel.project_dir%/vendor/tea/and-coffee/src/Migrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations
```
Does not work:
> Invalid type for path "doctrine_migrations.dir_name". Expected scalar, but got array.
