### ISSUE TITLE
Configuration used by CLI commands is ignored

### ISSUE THREAD

**Issue by emodric** [doctrine/DoctrineMigrationsBundle#311]
It seems that CLI commands ignore the `--configuration` parameter passed to them and instead use the globally configured migrations.

My `config/packages/doctrine_migrations.yaml` (`src/Migrations` is an empty folder):

```
doctrine_migrations:
    migrations_paths:
        'App\Migrations': 'src/Migrations'
```

My configuration used with CLI (notice how I added `name` as a test, which would make the config fail to parse), also tried adding the root config `doctrine_migrations`:

```
name: My Vendor Lib Migrations
migrations_paths:
    Vendor\Lib\Migrations\Doctrine: Doctrine
storage:
    table_storage:
        table_name: mylib_migration_versions
```

So when I run:

```
php bin/console doctrine:migrations:migrate --configuration=vendor/my/lib/migrations/doctrine.yaml
```

Instead of ignoring the globally configured migrations in favor of the config provided via CLI, I get the following:

```
In NoMigrationsToExecute.php line 14:

  Could not find any migrations to execute.


In NoMigrationsFoundWithCriteria.php line 14:

  Could not find any migrations matching your criteria (last).
```

This indicates that the global config is used (the one without migrations) instead of the CLI one.
