### ISSUE TITLE
The parameter "doctrine_migrations.dir_name" has a dependency on a non-existent parameter "kernel.root_dir"

### ISSUE THREAD

**Issue by realdo-msk** [doctrine/DoctrineMigrationsBundle#324]
Hi.
I'm trying to update my project from Symfony 4.4.x to 5.0.x
during update I receive the error:

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ParameterBag.php line 98:
!!                                                                                 
!!    The parameter "doctrine_migrations.dir_name" has a dependency on a non-exis  
!!    tent parameter "kernel.root_dir". Did you mean one of these: "kernel.projec  
!!    t_dir", "kernel.cache_dir", "kernel.logs_dir"?                               
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd

I'm not using parameter "kernel.root_dir" in my project, in configuration file, etc...

my version of doctrine-migrations-bundle is 2.1.2

**Comment by goetas** [comment]
This is because you did not specify any `doctrine_migrations.dir_name` parameter in your config file. You can define it and the error will be gone. 
This issue has been already solved in the upcoming 3.x version

**Comment by egorzot** [comment]
> This is because you did not specify any `doctrine_migrations.dir_name` parameter in your config file. You can define it and the error will be gone.

Didn't work for me. My config:
```
doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Infrastructure/Database/Migration'
    migrations_paths:
        App\Infrastructure\Database\Migration: '%kernel.project_dir%/src/Infrastructure/Database/Migration'
    all_or_nothing: true
    connection: default
    check_database_platform: true
    storage:
        table_storage:
            table_name: 'migration_versions'
            version_column_name: 'version'
            version_column_length: 1024
            executed_at_column_name: 'executed_at'
            execution_time_column_name: 'execution_time'
```
The error is 
```
The parameter "doctrine_migrations.dir_name" has a dependency on a non-existent parameter "kernel.root_dir". Did you mean one of these: "kernel.project_dir", "kernel.build_dir", "kernel.cache_dir", "kernel.logs_dir"?
```

Bundle version is `2.2.1`

I can't update to 3.x version. What should I do ?
