### ISSUE TITLE
Upgrade From 2.x to 3.0.0

### ISSUE THREAD

**Issue by tarlepp** [doctrine/DoctrineMigrationsBundle#329]
Currently `UPGRADE.md` doesn't mention that `./bin/console doctrine:migrations:sync-metadata-storage` command should be executed - is there some reason for this or is the documention just missing this part?

**Comment by corlanalexandru** [comment]
For me, it doesn't work to run the command php bin/console doctrine:migrations:sync-metadata-storage

**Comment by tarlepp** [comment]
> For me, it doesn't work to run the command php bin/console doctrine:migrations:sync-metadata-storage

weird, that did the trick for my application - do you get some error from that command?

**Comment by corlanalexandru** [comment]
I updated the configuration file
doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
    storage:
        table_storage:
            table_name: 'migration_versions'
            version_column_name: 'version'
            version_column_length: 1024
            executed_at_column_name: 'executed_at'

**Comment by corlanalexandru** [comment]
But i get the same error to run the sync-metadata-storage

**Comment by corlanalexandru** [comment]
Can you share your doctrine_migrations.yaml file?

**Comment by tarlepp** [comment]
what _is_ the actual error?

**Comment by corlanalexandru** [comment]
The metadata storage is not up to date, please run the sync-meta  
  data-storage command to fix this issue.

**Comment by tarlepp** [comment]
> Can you share your doctrine_migrations.yaml file?

sure,
```yaml
doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
    storage:
        table_storage:
            table_name: 'migration_versions'
            version_column_name: 'version'
            version_column_length: 512
            executed_at_column_name: 'executed_at'
```

I needed to adjust that `version_column_length` from `1024` to `512` just because I'm using MySQL 5.7 which have known problem with index sizes.

Also note that you could get more information about that error if you add `-vvv` option to that command.
