### ISSUE TITLE
Using dependency injection with 3.0.1

### ISSUE THREAD

**Issue by stingus** [doctrine/DoctrineMigrationsBundle#336]
This issue is related to #314 and I followed @goetas blog post https://www.goetas.com/blog/multi-namespace-migrations-with-doctrinemigrations-30/ to have some services injected into the migrations factory.

I keep getting the following error in the container cache `var/cache/dev/ContainerSwW75qg/getDoctrine_Migrations_DependencyFactoryService.php`:
```
In getDoctrine_Migrations_DependencyFactoryService.php line 38:                                                             
Maximum function nesting level of '256' reached, aborting!
```
The culprit line is
```
return ($container->privates['App\\Core\\ProjectVersionFactory'] ?? $container->load('getProjectVersionFactoryService'));
```
and after debugging it, looks like the `$container->privates['App\\Core\\ProjectVersionFactory']` is null. This leads to the recursive call.

This is the doctrine_migrations.yaml:
```
doctrine_migrations:
  migrations_paths:
    'DoctrineMigrations': '%kernel.project_dir%/migrations'
  organize_migrations: 'BY_YEAR'
  services:
    'Doctrine\Migrations\Version\MigrationFactory': 'App\Core\ProjectVersionFactory'
```
and the services.yaml:
```
...
  App\Core\ProjectVersionFactory.inner:
    class: Doctrine\Migrations\Version\DbalMigrationFactory
    factory: ['@doctrine.migrations.dependency_factory', 'getMigrationFactory']

  App\Core\ProjectVersionFactory:
    arguments: ['@App\Core\ProjectVersionFactory.inner', '@service_container']
```

Any ideas on how to fix this?
