### ISSUE TITLE
[error] Error thrown while running command "doctrine:migrations:migrate". Message: "The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue."

### ISSUE THREAD

**Issue by HashtagAssist** [doctrine/DoctrineMigrationsBundle#337]
I followed the tutorial from https://symfony.com/doc/current/doctrine.html. with a
Local Setup of XAMPPs MySQL and a new created Symfony project.

while running the migration "php bin/console doctrine:migrations:migrate" i got the error:
[error] Error thrown while running command "doctrine:migrations:migrate". Message: "The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue."

I tried to run sync-metadata-storage command but got the same error.

After a few people got the same error and asking about on StackOverfolw I think there is a problem withe the latest Version. 

The problem was solved by delete the lines 191 -195

```
$expectedTable = $this->getExpectedTable();

        if ($this->needsUpdate($expectedTable) !== null) {
            throw MetadataStorageError::notUpToDate();
        }
```
temporally from vendor\doctrine\migrations\lib\Doctrine\Migrations\Metadata\Storage\TableMetadataStorage.php. Run the command doctrine:migrations:migrate again and paste the lines back.
Now it seems to works to create new entities and migrate the changes.

**Comment by treztreiz** [comment]
Same problem here :)

**Comment by HashtagAssist** [comment]
It works if i change the DATABASE_URL in .env 

DATABASE_URL=mysql://root:@127.0.0.1:3306/testtest?serverVersion=10.4.11
to
DATABASE_URL=mysql://root:@127.0.0.1:3306/testtest?serverVersion=mariadb-10.4.11


Symfony documentation suggest specifying the version number but not the database type 

"There are more options in config/packages/doctrine.yaml that you can configure, including your server_version (e.g. 5.7 if you're using MySQL 5.7), which may affect how Doctrine functions."
https://symfony.com/doc/current/doctrine.html

**Comment by pawellen** [comment]
Adding serverVersion=mariadb-10.4.11 helped on one environment but on another one didn't. 

Running sync-metadata-storage  command on empty database causes error: 
"The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue"

somethig is wrong with this command, at least it should print some kind of info what was wrong.

**Comment by LaurieReinette** [comment]
Very helpful for me too, thank you very much

**Comment by Scott-Tresor** [comment]
pour quoi ce changement de doctrine affecte la manière de travailler sur la nouvelle version de symfony

**Comment by houssem789** [comment]
after restarting server , every think worked fine using this config : 

`doctrine_migrations:
    # List of namespace/path pairs to search for migrations, at least one required
    migrations_paths:
        "DoctrineMigrations": "%kernel.project_dir%/migrations"

    # List of additional migration classes to be loaded, optional

    # Connection to use for the migrations
    connection: default

    # Entity manager to use for migrations. This overrides the "connection" setting.

    storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
            table_name: "doctrine_migration_versions"
            version_column_name: "version"
            version_column_length: 1024
            executed_at_column_name: "executed_at"
            execution_time_column_name: "execution_time"

    # Possible values: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    organize_migrations: false

    # Path to your custom migrations template
    custom_template: ~

    # Run all migrations in a transaction.
    all_or_nothing: false

    # Adds an extra check in the generated migrations to ensure that is executed on the same database type.
    check_database_platform: true`

**Comment by Cartman34** [comment]
If setting the serverVersion is not working, it means the version you are specifying is invalid, this is not the version the server is communicating with.

**Comment by equapro** [comment]
Same error when updating to 3.0.1 version.
MariaDB server, version 10.5.5

In our case, the problem was the name of the database. It contained a hyphen (eg `data-base`).
`mysql://user:pass@127.0.0.1:3306/data-base?serverVersion=mariadb-10.5.5`

Rename the database solved the problem 
`mysql://user:pass@127.0.0.1:3306/data_base?serverVersion=mariadb-10.5.5`

PS: we tried replacing the hyphen with `%2D` in the url string but without success

**Comment by Mariyo** [comment]
Hi,

can you help me to fix simillar issue but with custom integration? My code uses existing PDO instance, this is my configuration:

```php
$dependencyFactory = DependencyFactory::fromConnection(
    new ConfigurationArray(
        [
            'table_storage'           => [
                'table_name'                 => 'doctrine_migration_versions',
                'version_column_name'        => 'version',
                'version_column_length'      => 1024,
                'executed_at_column_name'    => 'executed_at',
                'execution_time_column_name' => 'execution_time',
            ],
            'migrations_paths'        => [
                'Esopa\Migrations' => __DIR__ . '/../app/Esopa/Migrations',
            ],
            'all_or_nothing'          => true,
            'check_database_platform' => true,
        ]
    ),
    new ExistingConnection(
        DriverManager::getConnection(
            [
                'pdo' => $ci->get(PDO::class),
            ]
        )
    )
);

$cli = new Application('Doctrine Migrations');
$cli->setCatchExceptions(true);
$cli->addCommands(
    [
        new Command\DumpSchemaCommand($dependencyFactory),
        new Command\ExecuteCommand($dependencyFactory),
        new Command\GenerateCommand($dependencyFactory),
        new Command\LatestCommand($dependencyFactory),
        new Command\ListCommand($dependencyFactory),
        new Command\MigrateCommand($dependencyFactory),
        new Command\RollupCommand($dependencyFactory),
        new Command\StatusCommand($dependencyFactory),
        new Command\SyncMetadataCommand($dependencyFactory),
        new Command\VersionCommand($dependencyFactory),
    ]
);

$cli->run();
```

Error:

![image](https://user-images.githubusercontent.com/1678254/94821614-0d07e900-0402-11eb-97bf-a7a1ac15c247.png)

This is the place of error with more info about context:

![image](https://user-images.githubusercontent.com/1678254/94822258-bd75ed00-0402-11eb-9289-8184c834e8e4.png)

**Comment by goetas** [comment]
@Mariyo  Since you are providing a PDO connection, dbl might have problems detecting the platform (database engine type).
I suggest that you pass the `platform` option or at least the `serverVersion` option that will help dbal to create the right platform object used for the diffs.

**Comment by Mariyo** [comment]
@goetas Thank you for advice, `serverVersion` solved the issue. Funny thing is that I tried it before, but as `server_version`.

This setup works:

```php
$dependencyFactory = DependencyFactory::fromConnection(
    new ConfigurationArray(
        [
            'table_storage'           => [
                'table_name'                 => 'doctrine_migration_versions',
                'version_column_name'        => 'version',
                'version_column_length'      => 1024,
                'executed_at_column_name'    => 'executed_at',
                'execution_time_column_name' => 'execution_time',
            ],
            'migrations_paths'        => [
                'Esopa\Migrations' => __DIR__ . '/../app/Esopa/Migrations',
            ],
            'all_or_nothing'          => true,
            'check_database_platform' => true,
        ]
    ),
    new ExistingConnection(
        DriverManager::getConnection(
            [
                'pdo' => $ci->get(PDO::class),
                'serverVersion' => 'mariadb-10.3.12',
            ]
        )
    )
);

$cli = new Application('Doctrine Migrations');
$cli->setCatchExceptions(true);
$cli->addCommands(
    [
        new Command\DumpSchemaCommand($dependencyFactory),
        new Command\ExecuteCommand($dependencyFactory),
        new Command\GenerateCommand($dependencyFactory),
        new Command\LatestCommand($dependencyFactory),
        new Command\ListCommand($dependencyFactory),
        new Command\MigrateCommand($dependencyFactory),
        new Command\RollupCommand($dependencyFactory),
        new Command\StatusCommand($dependencyFactory),
        new Command\SyncMetadataCommand($dependencyFactory),
        new Command\VersionCommand($dependencyFactory),
    ]
);

$cli->run();
```

**Comment by GhostvOne** [comment]
Same here. Thanks for tip it works fine now.

**Comment by AhmedJemili** [comment]
Thanks, the problem was solved.

**Comment by boogiebit** [comment]
The solution of @HashtagAssist did the trick for me

**Comment by mike-ionut-mihai-sandu-tao** [comment]
same for me , great response 
btw : my fix : `?serverVersion=mariadb-10.5.8`

**Comment by crmpicco** [comment]
The first thing to try would be to run `bin/console doctrine:migrations:sync-metadata-storage` and go from there. That's all I needed to do.

**Comment by thePanz** [comment]
I created https://github.com/doctrine/DoctrineMigrationsBundle/pull/398 to mention this failure on the DoctrineMigrationsBundle v3 documentation on symfony.org and (one) proposed solution.

Please have a look, and add your comments :)

**Comment by martinlillemets** [comment]
I have been battling this issue for a few hours now. All of the above mentioned fixes did not work for me.
I managed to reproduce this from a clean symfony install.

I ran the following commands and the last command will produce error
I have added `print_r($this->platform->getAlterTableSQL($this->needsUpdate($expectedTable)));` to TableMetadataStorage:216 to provide additional information about the failure
```
bin/console doc:database:create
bin/console doctrine:migrations:sync-metadata-storage
bin/console make:entity User --no-interaction
bin/console doc:mig:diff
```
Terminal output
```
www-data@64b06799efef:~/html$ bin/console doc:database:create
Created database `tashis` for connection named default
www-data@64b06799efef:~/html$ bin/console doctrine:migrations:sync-metadata-storage

                                                                                                                        
 [OK] Metadata storage synchronized                                                                                     
                                                                                                                        

www-data@64b06799efef:~/html$ bin/console make:entity User --no-interaction

 created: src/Entity/User.php
 created: src/Repository/UserRepository.php
 
 Entity generated! Now let's add some fields!
 You can always add more fields later manually or by re-running this command.


           
  Success! 
           

 Next: When you're ready, create a migration with php bin/console make:migration
 
www-data@64b06799efef:~/html$ bin/console doc:mig:diff
Array
(
    [0] => ALTER TABLE doctrine_migration_versions CHANGE executed_at executed_at DATETIME DEFAULT NULL, CHANGE execution_time execution_time INT DEFAULT NULL
)
[critical] Error thrown while running command "'doc:mig:diff'". Message: "The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue."


In MetadataStorageError.php line 13:
                                                                                                           
  The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.  
                                                                                                           

doctrine:migrations:diff [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--namespace NAMESPACE] [--filter-expression FILTER-EXPRESSION] [--formatted] [--line-length LINE-LENGTH] [--check-database-platform [CHECK-DATABASE-PLATFORM]] [--allow-empty-diff] [--from-empty-schema]
```

My configuration:
PHP: 8.0.8
doctrine/doctrine-bundle: 2.4.2
doctrine/doctrine-migrations-bundle: 3.1.1
```
# .env.local
DATABASE_URL=mysql://admin:admin@db_server:3306/tashis?serverVersion=10.4.20
```
```yaml
#doctrine.yaml
doctrine:
    dbal:
        driver: 'pdo_mysql'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```
```yaml
#doctrine_migrations.yaml
doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'

```

Database is a simple docker image with the following configuration
```yml
#docker-compose.yml
version: '3.5'
services:
  db_server:
    image: mariadb:10.4
    container_name: '${APP_NAME}_db'
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - net_tashis
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
```
Any help is highly appreciated.

**Comment by thePanz** [comment]
@martinlillemets did you try with `?serverVersion=mariadb-10.4.20` in your DATABASE_URL configuration? (ref: `mariadb-` is missing from your example)

**Comment by martinlillemets** [comment]
@thePanz I checked and you are absolutely correct, i changed it and lo and behold, it works.  :man_facepalming: 
I could've sworn i tried it multiple times, and i even had a commented out version of DATABASE_URL in my .env with correct syntax.

**Comment by shivneutral** [comment]
thank you #HashtagAssist 
in my .env
DATABASE_URL=mysql://root:@127.0.0.1:3306/testtest?serverVersion=10.4.11
to
DATABASE_URL=mysql://root:@127.0.0.1:3306/testtest?serverVersion=mariadb-10.4.11
it is working

**Comment by DevDisco** [comment]
I am having similar issues.
I can create a new database and when I use `bin/console make:entity Subscriber`, src/Entity/Subscriber2.php and src/Repository/Subscriber2Repository.php are indeed created. However, when I try to add some fields I get this:

```
[critical] Error thrown while running command "make:entity Subscriber". Message: "Undefined constant Doctrine\DBAL\Types\Type::JSON_ARRAY"

In MakeEntity.php line 379:
  Undefined constant Doctrine\DBAL\Types\Type::JSON_ARRAY 
```

What am I doing wrong?

My setup: 

Windows 10, XAMPP, PHP: 8.0.2, MariaDB: 10.4.17, Symfony 5.3

.env
```
###> symfony/framework-bundle ###
APP_ENV=dev
APP_SECRET=d97ffeb5b8d028ecf2f1ed92d009d08f
###< symfony/framework-bundle ###

###> doctrine/doctrine-bundle ###
DATABASE_URL="mysql://symfony:1234@127.0.0.1:3306/symfony2?serverVersion=mariadb-10.4.17"
###< doctrine/doctrine-bundle ###
```

doctrine.yaml
```
doctrine:
  dbal:
    driver: "pdo_mysql"
    charset: utf8mb4
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_unicode_ci
    url: "%env(resolve:DATABASE_URL)%"

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: "%kernel.project_dir%/src/Entity"
        prefix: 'App\Entity'
        alias: App
```

docker-compose.yaml
```
#docker-compose.yaml
version: "3.5"
services:
  db_server:
    image: mariadb:10.4
    container_name: "${APP_NAME}_db"
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASS}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASS}"
      MYSQL_DATABASE: "${MYSQL_DB}"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
```

docker-compose.override.yaml
```
version: "3"

services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3206"
###< doctrine/doctrine-bundle ###
```

**Comment by sebbio** [comment]
> I am having similar issues. I can create a new database and when I use `bin/console make:entity Subscriber`, src/Entity/Subscriber2.php and src/Repository/Subscriber2Repository.php are indeed created. However, when I try to add some fields I get this:
> 
> ```
> [critical] Error thrown while running command "make:entity Subscriber". Message: "Undefined constant Doctrine\DBAL\Types\Type::JSON_ARRAY"
> 
> In MakeEntity.php line 379:
>   Undefined constant Doctrine\DBAL\Types\Type::JSON_ARRAY 
> ```
> 
> What am I doing wrong?
> 
> My setup:
> 
> Windows 10, XAMPP, PHP: 8.0.2, MariaDB: 10.4.17, Symfony 5.3
> 
> .env
> 
> ```
> ###> symfony/framework-bundle ###
> APP_ENV=dev
> APP_SECRET=d97ffeb5b8d028ecf2f1ed92d009d08f
> ###< symfony/framework-bundle ###
> 
> ###> doctrine/doctrine-bundle ###
> DATABASE_URL="mysql://symfony:1234@127.0.0.1:3306/symfony2?serverVersion=mariadb-10.4.17"
> ###< doctrine/doctrine-bundle ###
> ```
> 
> doctrine.yaml
> 
> ```
> doctrine:
>   dbal:
>     driver: "pdo_mysql"
>     charset: utf8mb4
>     default_table_options:
>       charset: utf8mb4
>       collate: utf8mb4_unicode_ci
>     url: "%env(resolve:DATABASE_URL)%"
> 
>     # IMPORTANT: You MUST configure your server version,
>     # either here or in the DATABASE_URL env var (see .env file)
>     #server_version: '13'
>   orm:
>     auto_generate_proxy_classes: true
>     naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
>     auto_mapping: true
>     mappings:
>       App:
>         is_bundle: false
>         type: annotation
>         dir: "%kernel.project_dir%/src/Entity"
>         prefix: 'App\Entity'
>         alias: App
> ```
> 
> docker-compose.yaml
> 
> ```
> #docker-compose.yaml
> version: "3.5"
> services:
>   db_server:
>     image: mariadb:10.4
>     container_name: "${APP_NAME}_db"
>     restart: always
>     ports:
>       - "${DB_PORT}:3306"
>     environment:
>       MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASS}"
>       MYSQL_USER: "${MYSQL_USER}"
>       MYSQL_PASSWORD: "${MYSQL_PASS}"
>       MYSQL_DATABASE: "${MYSQL_DB}"
>     volumes:
>       - db_data:/var/lib/mysql
>     healthcheck:
>       test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
>       interval: 5s
>       retries: 5
>     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
> ```
> 
> docker-compose.override.yaml
> 
> ```
> version: "3"
> 
> services:
>   ###> doctrine/doctrine-bundle ###
>   database:
>     ports:
>       - "3206"
> ###< doctrine/doctrine-bundle ###
> ```

confirm

**Comment by JackP74** [comment]
> 
> 
> I am having similar issues. I can create a new database and when I use `bin/console make:entity Subscriber`, src/Entity/Subscriber2.php and src/Repository/Subscriber2Repository.php are indeed created. However, when I try to add some fields I get this:
> 
> ```
> [critical] Error thrown while running command "make:entity Subscriber". Message: "Undefined constant Doctrine\DBAL\Types\Type::JSON_ARRAY"
> 
> In MakeEntity.php line 379:
>   Undefined constant Doctrine\DBAL\Types\Type::JSON_ARRAY 
> ```
> 
> What am I doing wrong?
> 
> My setup:
> 
> Windows 10, XAMPP, PHP: 8.0.2, MariaDB: 10.4.17, Symfony 5.3
> 
> .env
> 
> ```
> ###> symfony/framework-bundle ###
> APP_ENV=dev
> APP_SECRET=d97ffeb5b8d028ecf2f1ed92d009d08f
> ###< symfony/framework-bundle ###
> 
> ###> doctrine/doctrine-bundle ###
> DATABASE_URL="mysql://symfony:1234@127.0.0.1:3306/symfony2?serverVersion=mariadb-10.4.17"
> ###< doctrine/doctrine-bundle ###
> ```
> 
> doctrine.yaml
> 
> ```
> doctrine:
>   dbal:
>     driver: "pdo_mysql"
>     charset: utf8mb4
>     default_table_options:
>       charset: utf8mb4
>       collate: utf8mb4_unicode_ci
>     url: "%env(resolve:DATABASE_URL)%"
> 
>     # IMPORTANT: You MUST configure your server version,
>     # either here or in the DATABASE_URL env var (see .env file)
>     #server_version: '13'
>   orm:
>     auto_generate_proxy_classes: true
>     naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
>     auto_mapping: true
>     mappings:
>       App:
>         is_bundle: false
>         type: annotation
>         dir: "%kernel.project_dir%/src/Entity"
>         prefix: 'App\Entity'
>         alias: App
> ```
> 
> docker-compose.yaml
> 
> ```
> #docker-compose.yaml
> version: "3.5"
> services:
>   db_server:
>     image: mariadb:10.4
>     container_name: "${APP_NAME}_db"
>     restart: always
>     ports:
>       - "${DB_PORT}:3306"
>     environment:
>       MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASS}"
>       MYSQL_USER: "${MYSQL_USER}"
>       MYSQL_PASSWORD: "${MYSQL_PASS}"
>       MYSQL_DATABASE: "${MYSQL_DB}"
>     volumes:
>       - db_data:/var/lib/mysql
>     healthcheck:
>       test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
>       interval: 5s
>       retries: 5
>     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
> ```
> 
> docker-compose.override.yaml
> 
> ```
> version: "3"
> 
> services:
>   ###> doctrine/doctrine-bundle ###
>   database:
>     ports:
>       - "3206"
> ###< doctrine/doctrine-bundle ###
> ```

same problem

**Comment by DevDisco** [comment]
> 
> 
> > I am having similar issues. I can create a new database and when I use `bin/console make:entity Subscriber`, src/Entity/Subscriber2.php and src/Repository/Subscriber2Repository.php are indeed created. However, when I try to add some fields I get 
[....]
> 
> confirm

Does this mean I have to do something or that you have the same issue?

**Comment by alexgit2k** [comment]
See https://github.com/symfony/maker-bundle/issues/998

**Workaround**
`sed -i 's/Type::JSON_ARRAY/"json_array"/' vendor/symfony/maker-bundle/src/Maker/MakeEntity.php`

**Comment by ragusa87** [comment]
I have "almost" the same issue with MariaDB 10.5.12

* set database_version to  'mariadb-10.5.12'
* I can run "doctrine:migrations:sync-metadata-storage" successfully
* I got an exception whenever I browse the website:

Exception:
>The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.
```json
{"code":0,"message":"The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.","stack":"#0 \/var\/www\/html\/vendor\/doctrine\/migrations\/lib\/Doctrine\/Migrations\/Metadata\/Storage\/TableMetadataStorage.php(216): Doctrine\\Migrations\\Exception\\MetadataStorageError::notUpToDate()\n#1 \/var\/www\/html\/vendor\/doctrine\/migrations\/lib\/Doctrine\/Migrations\/Metadata\/Storage\/TableMetadataStorage.php(89): Doctrine\\Migrations\\Metadata\\Storage\\TableMetadataStorage-\u003EcheckInitialization()\n#2 \/var\/www\/html\/vendor\/doctrine\/doctrine-migrations-bundle\/Collector\/MigrationsCollector.php(32): Doctrine\\Migrations\\Metadata\\Storage\\TableMetadataStorage-\u003EgetExecutedMigrations()\n#3 \/var\/www\/html\/vendor\/symfony\/http-kernel\/Profiler\/Profiler.php(161): Doctrine\\Bundle\\MigrationsBundle\\Collector\\MigrationsCollector-\u003Ecollect(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\Response), NULL)\n#4 \/var\/www\/html\/vendor\/symfony\/http-kernel\/EventListener\/ProfilerListener.php(89): Symfony\\Component\\HttpKernel\\Profiler\\Profiler-\u003Ecollect(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\Response), NULL)\n#5 \/var\/www\/html\/vendor\/symfony\/event-dispatcher\/Debug\/WrappedListener.php(117): Symfony\\Component\\HttpKernel\\EventListener\\ProfilerListener-\u003EonKernelResponse(Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent), \u0027kernel.response\u0027, Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))\n#6 \/var\/www\/html\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php(230): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener-\u003E__invoke(Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent), \u0027kernel.response\u0027, Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))\n#7 \/var\/www\/html\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php(59): Symfony\\Component\\EventDispatcher\\EventDispatcher-\u003EcallListeners(Array, \u0027kernel.response\u0027, Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent))\n#8 \/var\/www\/html\/vendor\/symfony\/event-dispatcher\/Debug\/TraceableEventDispatcher.php(151): Symfony\\Component\\EventDispatcher\\EventDispatcher-\u003Edispatch(Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent), \u0027kernel.response\u0027)\n#9 \/var\/www\/html\/vendor\/symfony\/http-kernel\/HttpKernel.php(190): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher-\u003Edispatch(Object(Symfony\\Component\\HttpKernel\\Event\\ResponseEvent), \u0027kernel.response\u0027)\n#10 \/var\/www\/html\/vendor\/symfony\/http-kernel\/HttpKernel.php(178): Symfony\\Component\\HttpKernel\\HttpKernel-\u003EfilterResponse(Object(Symfony\\Component\\HttpFoundation\\Response), Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#11 \/var\/www\/html\/vendor\/symfony\/http-kernel\/HttpKernel.php(79): Symfony\\Component\\HttpKernel\\HttpKernel-\u003EhandleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#12 \/var\/www\/html\/vendor\/symfony\/http-kernel\/Kernel.php(199): Symfony\\Component\\HttpKernel\\HttpKernel-\u003Ehandle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#13 \/var\/www\/html\/vendor\/symfony\/runtime\/Runner\/Symfony\/HttpKernelRunner.php(37): Symfony\\Component\\HttpKernel\\Kernel-\u003Ehandle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 \/var\/www\/html\/vendor\/autoload_runtime.php(35): Symfony\\Component\\Runtime\\Runner\\Symfony\\HttpKernelRunner-\u003Erun()\n#15 \/var\/www\/html\/public\/index.php(6): require_once(\u0027\/var\/www\/html\/v...\u0027)\n#16 {main}"}
```

Schema:
```sql
-- auto-generated definition
create table migration_versions
(
    version        varchar(191) not null
        primary key,
    executed_at    datetime     null,
    execution_time int          null
)
    collate = utf8_unicode_ci;
```


Configuration:
```yml
doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    storage:
        table_storage:
            table_name: migration_versions
    enable_profiler: '%kernel.debug%'
```

Problem:
The schema is detected as not in sync as the default value is compared differently between `null` and `"NULL"`.

From in vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Comparator.php#L468
![image](https://user-images.githubusercontent.com/1695207/141377834-e1d42696-475a-4d8b-8a77-8a9c5b5afcb9.png)
![image](https://user-images.githubusercontent.com/1695207/141377871-ee96c1a4-aa15-4b0e-8504-9236f2f782de.png)

The sync-metadata-storage command runs the following query, who has not effect:
> ALTER TABLE migration_versions CHANGE executed_at executed_at DATETIME DEFAULT NULL, CHANGE execution_time execution_time INT DEFAULT NULL


Packages versions:
> doctrine/migrations                  3.1.4 
> doctrine/doctrine-migrations-bundle  3.1.1
> doctrine/dbal                        2.13.1 
> PHP 8.0.12
> mysql  Ver 15.1 Distrib 10.5.12-MariaDB, for Linux (x86_64) using readline 5.1

EDIT: Problem solved, setting the "DATABASE_VERSION" with the "mariadb" is the right solution. Just that I had to restart my container to fix the issue.
