### ISSUE TITLE
Specify entity manager for migrations on 3.0, since --em has been dropped

### ISSUE THREAD

**Issue by davrodrila** [doctrine/DoctrineMigrationsBundle#341]
Hello, 

First of all I hope this is the right place to put this kind of questions

I've been trying for a little bit to make a project work with 3.0 but couldn't.

So, the situation here is, I have two databases in the same project, and the way is set up there are two different entity managers that connect to the databases, so the app has **default** and **stats**. 

In order to have migrations working, I had a workaround that consisted of two configuration files:
**migrations_default.yaml**

```yml
migrations_directory: 'src/Migrations/Default/'
migrations_namespace: App\Migrations\Default
table_name: migration_versions
name: Application_Migrations_Default
```
and **migrations_stats.yaml**
```yml
migrations_directory: 'src/Migrations/Stats/'
migrations_namespace: App\Migrations\Stats
table_name: migration_versions
name: Application_Migrations_Stats
```

And what I did was launch the following command to migrate,,for the default EM:

`php bin/console doctrine:migrations:migrate --em=default --configuration=./migrations_default.yaml`

And for the Stats EM:

`php bin/console doctrine:migrations:migrate --em=stats --configuration=./migrations_stats.yaml`
This made it so the proper entity manager was used, and the migrations will each go into its own folder. 

However this no longer works in 3.0 as the --em parameter is no longer available, and I'm having a little bit of trouble making it work. I tried updating the config files to match the new version format, so the previous **migrations_default.yaml** will look something like this:
```yml
doctrine_migrations:
  migrations_paths:
    'App\Migrations\Default': 'src/Migrations/Default'
  em: default
```

And changed the command to:

`php bin/console doctrine:migrations:migrate --configuration=./migrations_default.yaml`

If I execute that, I get a "Migrations configuration key "doctrine_migrations" does not exist.  
" error, so it looks like I'm doing something wrong here, but I'm just not sure what is it. I followed [this manual](https://www.doctrine-project.org/projects/doctrine-migrations-bundle/en/3.0/index.html#configuration) to build the new config file format.

**Comment by goetas** [comment]
Related to https://github.com/doctrine/migrations/issues/1021

**Comment by goetas** [comment]
@davrodrila  Can you please explain a bit more in detail how are you using this feature? We had a team discussion on how to re-implement this in 3.0 and we wanted to see if there are ways to improve it (as example allowing to run migrations across all defined connections...?) Are you using the `--em` parameter to generate a per-entity-manger diff?

**Comment by mdeherder** [comment]
For my part, I use the `--em` parameter to generate a difference by manager-entity ?
I used `doctrine:migrations:diff` and `doctrine:migrations:migrate` with `--em` for entity-manager and `--configuration` for the migrations-paths option

**Comment by davrodrila** [comment]
Thanks, I'll do my best to explain, but It's pretty much what @goetas and @mdeherder said, It's so I can get diffs per entity manager. Each entity manager has its own connection to a different database.

This is because the app has two sets of entities, (Default and Stats) each one with its own database. The entities are placed on different folders. (src/Default/Entity and src/Stats/Entity), so in my doctrine.yaml looks like this:

```yml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_DEFAULT_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            stats:
                url: '%env(resolve:DATABASE_STATS_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: default
                mappings:
                    Default:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Default/Entity'
                        prefix: 'App\Default\Entity'
                        alias: Default
                    FOSOAuthServerBundle: ~
                    SonataUserBundle: ~
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
            stats:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: false
                connection: stats
                mappings:
                    analytics:
                        type: annotation
                        dir: '%kernel.project_dir%/src/Stats/Entity'
                        prefix: 'App\Stats\Entity'
                        alias: Stats
```

So with this setup I hope you can see the problem I was trying to solve with the --em and --configuration workaround. Since the doctrine migrations config doesnt really have a way to discriminate between the two entity managers, I just loaded different config files depending which entity manager I wanted to use. 

For example, what @dvc suggested [here](https://github.com/doctrine/DoctrineMigrationsBundle/issues/38#issuecomment-557424739) would fix my particular need for --em and different config files.
