### ISSUE TITLE
doctrine:migrations:diff generates DROP TABLE for messenger_messages table

### ISSUE THREAD

**Issue by darielvicedo** [doctrine/DoctrineMigrationsBundle#355]
After installing Messenger, successive migrations insert "DROP TABLE messenger_messages".

**Comment by dvdknaap** [comment]
I had the same issue and had to remove the lines by hand but it's fixed for me in the last version

**Comment by darielvicedo** [comment]
I solved this by ignoring the _messenger_messages_ table in the model using the **schema_filter** option:
```yaml
#doctrine.yaml
doctrine:
    dbal:
        schema_filter:  ~^(?!messenger_messages)~
```
But I'm not sure that this is the solution.
