### ISSUE TITLE
Symfony container linter complains about invalid definition

### ISSUE THREAD

**Issue by norkunas** [doctrine/DoctrineMigrationsBundle#413]
When running `lint:container` it returns:
```
 [ERROR] Invalid definition for service                                         
         "doctrine.migrations.dependency_factory": argument 2 of                
         "Doctrine\Migrations\DependencyFactory::setDefinition()" accepts       
         "callable",                                                            
         "Doctrine\Bundle\MigrationsBundle\MigrationsFactory\ContainerAwareMigra
         tionFactory" passed.                                            
```

**Comment by luca-rath** [comment]
Can confirm, this happens since version `3.1.0`, version `3.0.3` is working fine

**Comment by derrabus** [comment]
Same here. Because we run the linter as part of our CI, this issue is a blocker for us.

**Comment by goetas** [comment]
@derrabus @norkunas did any of you provide a custom migration factory? are you using the default bundle configs?

**Comment by derrabus** [comment]
My configuration looks like this:

```YAML
doctrine_migrations:
    migrations_paths:
        App\Migrations: '%kernel.project_dir%/migrations'
    storage:
        table_storage:
            table_name: migration_versions
```
