### ISSUE TITLE
Command doctrine:migrations:diff always generates same migration file even if there is no differences

### ISSUE THREAD

**Issue by fdiedler** [doctrine/DoctrineMigrationsBundle#468]
Hi,

I don't understand why when I run the command doctrine:migrations:diff I always have a migrations file even if my schema model has not changed.

In this filen the funciton up() is empty and the function down() has lines like : 

> ALTER TABLE address CHANGE street street VARCHAR(100) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`

I use Symfony 5.4 and MySql, my configuration file seems good : 
```
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```
With, DATABASE_URL="mysql://root:yyyy@127.0.0.1:3306/databaseName?charset=utf8mb4"

What is wrong ? 

Thanks
