### ISSUE TITLE
Doctrine Migration Bundle runs its own checks for the Messenger component?

### ISSUE THREAD

**Issue by DavidGarciaCat** [doctrine/DoctrineMigrationsBundle#485]
When I warm up the Symfony cache, I don't get any error:

```
bin/console cache:clear -vvv

 // Clearing the cache for the dev environment with debug true

 // Warming up cache...

 // Removing old build and cache directory...

 // Finished

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.
```

However, when I run the command to make a new migration including the diff changes on my ORM, I get the following error:

```
bin/console make:migration


In Connection.php line 106:

  Unknown option found: [exchange]. Allowed options are [table_name, queue_name, redeliver_timeout, auto_setup, use_notify, check_delayed_interval, get_notify_timeout].
```

My `messenger.yaml` file has the `exchange` option, as I needed to add it to solve an issue with the AMQP's RabbitMQ integration:

```yaml
framework:
    messenger:

        failure_transport: failed

        transports:

            async:
                dsn: '%env(MESSENGER_TRANSPORT_AMQP)%'
                options:
                    exchange:
                        name: async
                        type: direct
                retry_strategy:
                    max_retries: 0

            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DOCTRINE)%'
                options:
                    queue_name: failed

        routing:

            # ...
```

I don't understand why the Doctrine Migrations Bundle decides to check my Messenger configuration and decide that the settings I have are invalid, while the Messenger component itself does not return any error when warming up the cache or when running the queued messages.

Please advice on how it can be resolved on my end unless it's an issue with the code in this bundle that requires a new PR (if this is the case, would be nice to know when it can be expected, as it's causing a blocker at the moment).

Thank you,
