### ISSUE TITLE
Postgres - Generate migration only for public schema

### ISSUE THREAD

**Issue by orangevinz** [doctrine/DoctrineMigrationsBundle#549]
I'm using PostgreSQL v16 with extensions such as jobmon and partman.
Each time I run `make:migration`, it generates a new migration with extensions diffs.

With this configuration
```yaml
doctrine:
    dbal:
        default_connection:       default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                use_savepoints: true
                profiling_collect_backtrace: '%kernel.debug%'
                schema_filter: '~^(?!doctrine_migration_versions$|.*jobmon.*|.*partman.*|.*dblink.*)~'
```

The generated down method includes:

```php
public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA partman');
        $this->addSql('CREATE SCHEMA jobmon');
        $this->addSql('CREATE SCHEMA dblink');
        $this->addSql('CREATE SCHEMA public');
```

How can I restrict migrations to the public schema only ?
