### ISSUE TITLE
Does not use custom TypedFieldMapper

### ISSUE THREAD

**Issue by michnovka** [doctrine/DoctrineMigrationsBundle#557]
I have an issue with migrations, as they do not use my custom `TypedFieldMapper`.

I configure it like this in services.yaml:
```yaml
services:
    App\ORM\TypedFieldMapper\MyTypedFieldMapper:

    doctrine.orm.configuration:
        class: Doctrine\ORM\Configuration
        calls:
            - setTypedFieldMapper: [ '@App\ORM\TypedFieldMapper\MyTypedFieldMapper' ]
```

And this works fine when running the app. But when doing `doctrine:migrations:diff` then this is not used and instead `Doctrine\ORM\Mapping\DefaultTypedFieldMapper` is used.

How do I tell migration bundle to use my custom typed field mapper?

**Comment by michnovka** [comment]
I found that `Doctrine\Orm\Configuration::setTypedFieldMapper()` is called twice. First, correctly with the data configured in `services.yaml`. But then once again but with the `DefaultTypedFieldMapper`.

**Comment by michnovka** [comment]
Hmm, I think maybe this is not related to migrations at all. I checked `var/cache/dev/Container50KivA3/App_KernelDevDebugContainer.php` and I see it has function `getDoctrine_Orm_DefaultEntityManagerService` function.

Here, I have on top:
```php
        $a->setTypedFieldMapper(new \App\ORM\TypedFieldMapper\MyTypedFieldMapper());
        $a->setEntityNamespaces(['App' => 'App\\Entity']);
```
and then few lines below it
```php
        $a->setTypedFieldMapper(new \Doctrine\ORM\Mapping\DefaultTypedFieldMapper());
```

So, the issue is that my `setTypedFieldMapper` call from `services.yaml` is called before the one that overrides it.

Any ideas how to fix this please?

**Comment by michnovka** [comment]
Ok, so I guess this has to be implemented: https://github.com/doctrine/DoctrineBundle/issues/1696

I will close this issue, as it is unrelated to migrations, but please, anybody knows how I can call 

```
    doctrine.orm.configuration:
        class: Doctrine\ORM\Configuration
        calls:
            - WHATEVER
```

AFTER all the default ones are called?
