### ISSUE TITLE
get connection name in migration file

### ISSUE THREAD

**Issue by oskude** [doctrine/DoctrineMigrationsBundle#98]
we have to use different databases for some entities, depending on some factors. and to not migrate some entities to some databases, we use the following (manually added) in the migration files:
```php
$this->skipIf($this->connection->getDatabase() != "foobar");
```

but this is suboptiomal as that "foobar" is defined in parameters.yml, that the user is supposed to create (like on local devel system).

what would be nicer if we could do:
```php
$this->skipIf($this->connection->getName() != "barfoo");
```
where "barfoo" is defined in config.yml, that user is not supposed to edit, like:
```yml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
				dbname: "%database_name%"
                ...
            barfoo:
				dbname: "%database_name%_barfoo"
				...
```

was not sure if i should report this to "dbal" or "migrations" repo, so i reported it to the closest from user perspective.

*ps. or if there is an easier way to define "this entity should go only to these connections" or "this entity should never go to these connections", i would love to hear about that!*
